[package]
name = "diffrust"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.20", features = ["derive"] }
hex-literal = "0.4.1"
log = "0.4.22"
md5 = "0.7.0"
serde_json = "1.0.133"
tempfile = "3.14.0"
